version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - PORT=8000
    volumes:
      - data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_dist:/usr/share/nginx/html
    restart: unless-stopped

volumes:
  data:
  frontend_dist: